l/routes/web.php
//Route::post('/saveCard/{cardData}', 'Bookings\PaymentsController@saveCard');
// /alexx


Route::group(['prefix' => 'admin','middleware'=> 'admin','namespace' => 'Admin'],function() {

    Route::get('/', 'AdminController@adminHomePage')->name('adminHomePage');
    Route::resource('/user','User\UserController', ['except' => ['show']]);
    Route::get('/user/getCarerImage/{id}','User\UserController@getCarerImage');
    Route::get('/user/page/{p?}','User\UserController@index')->name('user_pagination');;
    Route::resource('/booking','Booking\BookingController', ['only' => ['index']]);
//    Route::get('/blog/{id}', 'Blog\BlogController@create');
    Route::resource('/blog','Blog\BlogController');
//    Route::resource('/tags','Blog\TagController');

    Route::get('/user/review_management','ReviewManagementController@index')->name('ReviewManagement');
    Route::post('/user/review_management','ReviewManagementController@index')->name('ReviewManagement');
    Route::get('/user/review_management/{id}','ReviewManagementController@edit')->name('ReviewManagementEdit');
    Route::post('/user/review_management/{id}','ReviewManagementController@edit')->name('ReviewManagementEdit');
  
  	Route::get('/user/reviewed_management','ReviewManagementController@reviewed')->name('ReviewedManagement');
  	Route::post('/user/reviewed_management','ReviewManagementController@reviewed')->name('ReviewedManagement');
  	Route::get('/user/reviewed_management/{id}','ReviewManagementController@reviewed_edit')->name('ReviewManagementEdited');
    Route::post('/user/reviewed_management/{id}','ReviewManagementController@reviewed_edit')->name('ReviewManagementEditrd');

    Route::get('/financial','FinancialController@index')->name('financial');
    Route::get('/statistic','StatisticController@index')->name('statistic');
    Route::get('/statistic/download','StatisticController@exportStaticticsToXls')->name('statisticDownload');
    Route::get('/fees','FeesController@index')->name('fees');
   Route::get('/liveincarer','LiveincarerController@index')->name('liveincareres'); 
   Route::post('/liveincarer','LiveincarerController@update')->name('liveincarerpost');
    Route::get('/post-codes','PostCodesController@index')->name('PostCodes');
    Route::post('/post-codes','PostCodesController@index')->name('PostCodesPost');
    Route::post('/fees','FeesController@update')->name('feespost');
    Route::get('/holidays','HolidaysController@index')->name('holidays');
    Route::post('/holidays','HolidaysController@update')->name('holidaysPost');
    Route::post('/holidays/delete/{id}','HolidaysController@delete')->name('holidaysDeletePost');

    Route::get('/settings','SettingsController@index')->name('settingsAdmin');
    Route::post('/settings','SettingsController@update')->name('settingsAdminPost');
    Route::delete('/settings/{id}', 'SettingsController@deleteAdmin')->name('settingsAdminDelete');
	
  	Route::get('/add-carer-wages','CarerWagesController@create')->name('CarerWagesAdd');
    Route::get('/carer-wages','CarerWagesController@index')->name('CarerWages');
    Route::post('/carer-wages','CarerWagesController@update')->name('CarerWagesPost');
  	Route::post('/save-carer-wages','CarerWagesController@save')->name('CarerWagesSave');
  


    Route::get('/booking-transactions', 'AdminSitePayment@getBookingTransactions')->name('BookingTransactions');
    Route::post('/booking-transactions', 'AdminSitePayment@getBookingTransactions')->name('BookingTransactionsPost');

    Route::get('/carer-payout', 'AdminSitePayment@getPayoutsToCarers')->name('PayoutsToCarers');
    //Route::post('/carer-payout/{booking}', 'AdminSitePayment@makePayoutToCarer')->name('makePayoutToCarer');
    Route::post('/carer-payout/{appointment_id}', 'AdminSitePayment@makePayoutToCarer')->name('makePayoutToCarer');

    Route::get('/purchaser-payout', 'AdminSitePayment@getPayoutsToPurchasers')->name('PayoutsToPurchasers');
    Route::post('/purchaser-payout/{booking}', 'AdminSitePayment@makePayoutToPurchaser')->name('makePayoutToPurchaser');
  

    Route::get('/dispute-payout', 'DisputePayoutsController@index')->name('DisputePayouts');
    Route::put('/dispute-payout/{dispute_payout_id}/detailsOfDispute', 'DisputePayoutsController@setDetailsOfDispute');
    Route::put('/dispute-payout/{dispute_payout_id}/detailsOfDisputeResolution', 'DisputePayoutsController@detailsOfDisputeResolution');
    Route::post('/dispute-payout/{dispute_payout_id}/payoutToCarer', 'DisputePayoutsController@payoutToCarer');
    Route::post('/dispute-payout/{dispute_payout_id}/payoutToPurchaser', 'DisputePayoutsController@payoutToPurchaser');

    Route::get('/bonuses-carers', 'BonusController@getBonusesCarer')->name('BonusesCarers');
    Route::get('/bonuses-purchasers', 'BonusController@getBonusesPurchaser')->name('BonusesPurchasers');
    Route::post('/payout-bonus/{bonus_id}', 'BonusController@payoutBonus');
    Route::post('/cancel-bonus/{bonus_id}', 'BonusController@cancelBonus');

    //alexx
    Route::get('/filterCarerWages/{carerId}/{filter}', 'CarerWagesController@filterCarerWages');
    //returns all appointment statuses of a booking
  
   //add export on all admin pages 
	Route::get('/booking/download','Booking\BookingController@exportBookingToXls')->name('bookingDownload');
	Route::get('/booking-transactions/download','AdminSitePayment@exportTransactionToXls')->name('bookingTransactionDownload');
	Route::get('/purchaser-payout/download','AdminSitePayment@exportPurchaserPaymentToXls')->name('purchaserPaymentDownload');
	Route::get('/carer-payout/download','AdminSitePayment@exportCarerPaymentToXls')->name('carerPaymentDownload');
	Route::get('/dispute-payout/download','DisputePayoutsController@exportDisputePayoutToXls')->name('disputePayoutsDownload');
	Route::get('/bonuses-carers/download','BonusController@exportBonusCarersToXls')->name('bonusCarersDownload');
	Route::get('/bonuses-purchasers/download','BonusController@exportBonusPurchaserToXls')->name('bonusPurchaserDownload');
Route::get('/booking/accountant-report-download','Booking\BookingController@exportAccountantReportToXls')->name('accountantReportDownload');
Route::resource('/page','Page\PageController');
Route::resource('/faq','Faq\FaqController');
Route::resource('/trust','Trust\TrustController');
Route::resource('/testimonial','Testimonial\TestimonialController');
Route::resource('/banner','Banner\BannerController');  
Route::get('/contact','Contact\ContactController@index')->name('contactget');
Route::post('/contact-update','Contact\ContactController@update')->name('contactpost');  
Route::get('/gdpr','User\UserController@UserGdpr')->name('gdpr');
Route::get('/gdpr/download','User\UserController@exportGdprToXls')->name('gdprDownload');
Route::get('/ip-monitoring','User\UserController@ipMonitoring')->name('IpMonitoring');
  
Route::get('/booking/{booking_id}/cancelBooking','Booking\BookingController@cancelBooking');
Route::get('/booking/{appointment_id}/cancelAppointment','Booking\BookingController@cancelAppointment');
Route::get('/bonuses-purchasers/credit-wallet/', 'BonusController@CreditWallet');  
  
});

Route::get('/check24/{date}/{time}', 'Bookings\BookingsController@appointmentIsMinimum24HoursAhead');

Route::post('/increase-postcode-search/{postcode}', 'SearchController@increasePostCode');
Route::get('/get-referral-code/{userId}', 'CarerController@getReferralCode');
Route::post('/update-referral-code/{userId}/{code}', 'CarerController@updateReferralCode');

Route::get('/test-cronjob', 'CarerController@testCronjob');


Route::get('/test_document_upload', function (){
    return view('test_document_upload');
});

Route::get('/appan', function (){
    return view('resources/views/Holm/purchaserProfiles/Booking/NewAnAppointment');
});

Route::get('/test_stripe', function (){
    $user = \App\User::find(2);
    $card = $user->credit_cards()->first();
    \App\Helpers\Facades\PaymentTools::createCharge(2000, $card->token, 209);
});

/*Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });*/

Route::get('/test', function () {
  
 // echo K1rkhnmmn=
   //return bcrypt('K1rkhnmmn=');
  $res = DB::select("SELECT a.id FROM appointments a JOIN bookings b ON a.booking_id = b.id WHERE UNIX_TIMESTAMP(a.date_start) = CURDATE() AND DATE_ADD(NOW(), INTERVAL 1 HOUR) > UNIX_TIMESTAMP(a.time_from) AND a.reminder_sent = 0 AND b.status_id = 5 AND a.status_id < 3");
  echo "<pre>"; print_r($res); echo "<pre>"; exit;
//    $pathes = [
//        'img/profile_photos',
//        'img/service_user_profile_photos',
//    ];
//
//    foreach ($pathes as $path) {
//        $photos = File::allFiles($path);
//        foreach ($photos as $photo) {
//            $name = $photo->getPathname();
//
//            try {
//                $img = Image::make($name);
//                $width = $img->width();
//                $height = $img->height();
//
//                if ($width / $height > 1) {
//                    // resize image to new width but do not exceed original size
//                    $img = $img->widen(112, function ($constraint) {
//                        $constraint->upsize();
//                    });
//                } else {
//                    // resize image to new height but do not exceed original size
//                    $img = $img->heighten(112, function ($constraint) {
//                        $constraint->upsize();
//                    });
//                }
//
//                $img->save($name);
//            } catch (\Exception $e) {
//                echo 'error ' . $name . '<br>';
//            }
//        }
//    }
//    $a = 1.3;
//    $b = 1.3;
//
//    $sum = $a + $b;
//
//    $a = \Carbon\Carbon::createFromFormat('H.i', $a);
//    $aa = $a->addHours($b);
//    dd($aa->diffInHours($a))
//    $b = \Carbon\Carbon::createFromFormat('H.i', $b);
////    $a = \Carbon\Carbon::parse($a);
//    $a->addHours($b);

l/app/Blog.php
<?php

namespace App;

use DateTime;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $fillable = ['title', 'body'];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

//    public function tags()
//    {
//        return $this->belongsToMany('App\Tag')->withTimestamps();
//    }

    public function getCreated_atAttribute($value){
        return date('d/m/Y',strtotime($value));
    }
}

l/resources/views/HolmAdmin/gdpr/GdprMails.blade.php
<!-- Messages table -->	
<div class="financialsCard" style="overflow-x: auto; max-height:500px">
	<div class="financialsCard__header">
		<div class="financialsCard__title" style="width: 100%;">
			<h4>
				Mails 
			</h4>
		</div>
		<div class="tableWrap tableWrap--margin-t">
		    <table class="adminTable">
		    	<thead>
					<td>Subject</td>
					<td>Date</td>
					<td>Content</td>
				</thead>
				<tbody>
					
				@if(count($mails)>0)
				   @foreach($mails as $mail)	
					<tr>
						<td>{{$mail->subject}}</td>
						<td>{{$mail->time_to_send}}</td>
						<td>
							<?php 
								 $text = preg_replace('#<style[^>]*>.*?</style>#si', '', $mail->text); 
								 $text = preg_replace('#<title[^>]*>.*?</title>#si', '', $text); 
								 echo  strip_tags($text); 
							 ?>
						</td>
					</tr>
					
					@endforeach
			   @endif		
				</tbody>
			</table>
		</div>			
		
	</div>
</div>		

l/resources/views/HolmAdmin/gdpr/GdprPurchaser.blade.php
<div class="financialsCard">
	<div class="financialsCard__header">
		<div class="financialsCard__title">
			<h2>
				Profile Details
			</h2>
		</div>
	</div>
	
	<div class="financialsCard__header"><h3>General</h3></div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> First Name</div>
		<div class="col-md-6">
		@if($user->first_name==null)
			--
		@else
			{{$user->first_name}}
		@endif
		</div>
	</div>

	<div class="row financialsCard__header">
		<div class="col-md-6"> Last Name </div>
		<div class="col-md-6">
		@if($user->family_name==null)
			--
		@else
			{{$user->family_name}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Gender </div>
		<div class="col-md-6">
		@if($user->gender==null)
			--
		@else
			{{$user->gender}}
		@endif
		</div>
	</div>
	<div class="row financialsCard__header">
		<div class="col-md-6"> Date of birth </div>
		<div class="col-md-6">
		@if($user->DoB==null)
			--
		@else
			{{$user->DoB}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> I like to be called </div>
		<div class="col-md-6">
		@if($user->like_name==null)
			--
		@else
			{{$user->like_name}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Own referral Code </div>
		<div class="col-md-6">
		@if($user->own_referral_code==null)
			--
		@else
			{{$user->own_referral_code}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Registered On </div>
		<div class="col-md-6">
		@if($user->created_at==null)
			--
		@else
			{{$user->created_at}}
		@endif
		</div>
	</div>
	
	<div class="financialsCard__header"><h3>Contact</h3></div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Address Line 1 </div>
		<div class="col-md-6">
		@if($user->address_line1==null)
			--
		@else
			{{$user->address_line1}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Address Line 2 </div>
		<div class="col-md-6">
		@if($user->address_line2==null)
			--
		@else
			{{$user->address_line2}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6">Town / city  </div>
		<div class="col-md-6">
		@if($user->town==null)
			--
		@else
			{{$user->town}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Post code</div>
		<div class="col-md-6">
		@if($user->postcode==null)
			--
		@else
			{{$user->postcode}}
		@endif
		</div>
	</div>
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Mobile Number</div>
		<div class="col-md-6">
		@if($user->mobile_number==null)
			--
		@else
			{{$user->mobile_number}}
		@endif
		</div>
	</div>
	
	
	
	
	<div class="row financialsCard__header">
		<div class="col-md-6"> Email Address</div>
		<div class="col-md-6">
		
			@if(isset($user->email) )
				--
			@else
				{{$user->email}}
			@endif
		</div>
	</div>
	


	<div class="financialsCard__header"><h3>Payment Details</h3></div>
		<div class="col-md-6"></div>
		<div class="col-md-6">
		
		@if(count($credit_card)> 0)
			@foreach($credit_card as $cc)
				xxxx xxxx xxxx {{$cc->last_four}}	
			@endforeach
		@else
			--
		@endif
		
		</div>

	<div class="financialsCard__header"><h3>People I Am Buying carer for</h3></div>
		<div class="col-md-6"></div>
		<div class="col-md-6">
		@if($service_user->count()>0)
			@foreach($service_user as $su)
				@if($su->deleted!='Yes')
					@if($su->first_name==null)
						<a target="_blank" href="{{route('gdpr')}}?userName={{$su->id}}">NA</a>,
					@else
						<a target="_blank" href="{{route('gdpr')}}?userName={{$su->id}}">{{$su->first_name}}</a>,
					@endif
				@endif
			@endforeach
		@else
			--
		@endif
		</div>
  </div>



	
	
<!-- Appointment table -->
<div class="financialsCard" style="overflow-x: auto; max-height:500px">
	<div class="financialsCard__header">
		<div class="financialsCard__title" style="width: 100%;">
			<h2>
				Appointment 
			</h2>
		</div>

		<div class="tableWrap tableWrap--margin-t">
		    <table class="adminTable">
		    	<thead>
		    		<tr class="extra-tr">
		    			<td class="for-inner">
			                <table class="innerTable ">
			                    <tr>
			                        <td class="">
			                            <span class="extraTitle">Appointment ID</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Date</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">From</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">To</span>
			                        </td>
									<td class="">
			                            <span class="extraTitle">Carer</span>
			                        </td>
									<td class="">
			                            <span class="extraTitle">Service User</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Status</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Amount</span>
			                        </td>
			                    </tr>
			                </table>
			            </td>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		<tr>
		    			<td class="for-inner">
		    				<table class="innerTable ">
		    				@foreach($purchaser_booking as $pb)
		 		    				@foreach($booking_appointment=$pb->appointments as $ba)
							            <tr>
							                <td class="">
							                    <span>{{$ba->id}}</span>
							                </td>
							                <td class="">
							                   {{$ba->date_start}}
							                </td>
							                <td class="">
							                   {{$ba->time_from}}
							                </td>
							                <td class="">
							                   {{$ba->time_to}}
							                </td>
											<td class="">
												{{$pb->bookingCarerProfile->first_name}} {{$pb->bookingCarerProfile->family_name}}
							                </td>
											<td class="">
												{{$pb->bookingServiceUser->first_name}} {{$pb->bookingServiceUser->family_name}}
							                </td>
							                <td class="">
							                	{{$ba->appointmentStatus->name}}
							                	
							                </td>
							                <td class="">
							                	<i class="fa fa-gbp" aria-hidden="true"></i>
							                   {{$ba->price_for_carer}}
							                </td>
							            </tr>
		    						@endforeach
					        @endforeach
					        </table>
		    			</td>
		    			<td class="for-inner">
		    			</td>
		    		</tr>
		    	</tbody>
		    </table>	
	    </div>
	</div>
</div>



<!-- Transaction table -->
<div class="financialsCard" style="overflow-x: auto; max-height:500px">
	<div class="financialsCard__header">
		<div class="financialsCard__title" style="width: 100%;">
			<h2>
				Transaction 
			</h2>
		</div>

		<div class="tableWrap tableWrap--margin-t">
		    <table class="adminTable">
		    	<thead>
		    		<tr class="extra-tr">
		    			<td class="for-inner">
			                <table class="innerTable ">
			                    <tr>
			                        <td class="">
			                            <span class="extraTitle">Transaction ID</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Date and Time</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Booking ID</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Amount</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Payment Type</span>
			                        </td>
			                        <td class="">
			                            <span class="extraTitle">Transaction Status</span>
			                        </td>
			                    </tr>
			                </table>
			            </td>
		    		</tr>
		    	</thead>
		    	<tbody>
		    		<tr>
		    			<td class="for-inner">
		    				<table class="innerTable ">
		    					@foreach($purchaser_transaction as $pt)
		    						    <tr>
							                <td class="">
							                    <span>{{$pt->id}}</span>
							                </td>
							                <td class="">
							                   	{{$pt->created_at}}
							                </td>
							                <td class="">
							                   	{{$pt->booking_id}}
							                </td>
							                <td class="">
							                	<i class="fa fa-gbp" aria-hidden="true"></i>
							                   	{{$pt->amount}}
							                </td>
							                <td class="">
							                @if($pt->payment_method=='stripe')
							                	Credit Card 
							                @else
							                	Bonuses Wallet 
							                @endif
							                	
							                </td>
							                <td class="">
							                  	completed
							                </td>
							            </tr>
		    						
		    					@endforeach
		    						
					        </table>
		    			</td>
		    			<td class="for-inner">
		    			</td>
		    		</tr>
		    	</tbody>
		    </table>	
	    </div>
	</div>
</div>

l/resources/views/HolmAdmin/gdpr/gdpr.blade.php
<div class="mainPanel">
    <h2 class="categoryTitle">
          <span class="categoryTitle__ico">
              <i class="fa fa-user-secret" aria-hidden="true"></i>
          </span>
        GDPR
    </h2>
    
    <div class="panelHead">
       <div class="panelHead__group">
			{!! Form::open(['method'=>'GET','route'=>'gdpr']) !!}
			 @if(count($user) > 1)
				<div><h3>Please select user or search by full name or id.</h3></div>
			   @endif
			<div class="filterBox">
				<div class="formField formField--fix-biger"style="margin-right: 10px">
					<div class="fieldWrap">
						{!! Form::text('userName',null,['class'=>'formItem formItem--input formItem--search','maxlength'=>'60','placeholder'=>'Search name']) !!}
					</div>
				</div>
				
				
		   @if(count($user) > 1)
			<div class="formField formField--fix-biger"style="margin-right: 10px">
			  <div class="fieldWrap">
			   <select name="userId" class="formItem formItem--select" id="gdprOption">
				   <option disable>Select User</option>
				 @foreach($user as $option)
				   <option value="{{$option->id}}">{{$option->first_name}} {{$option->family_name}}</option>
				 @endforeach
			   </select>
			 </div>
			</div>   
			
			@endif	

				{!! Form::submit('filter',['class'=>'actionsBtn actionsBtn--filter actionsBtn--bigger']) !!}
			</div>
			{!! Form::close()!!}
			
			@if(count($user) == 1)
			
				<a href="{{route('gdprDownload')}}?userName={{ app('request')->input('userName') }}" class="actionsBtn actionsBtn--filter actionsBtn--bigger">
					Export to CSV
				</a>
			
			@endif

        </div>
	</div>
	
	
	<div class="financialsContainer">

		@if(count($user)==1 && !empty($user))

			@if($user->user_type == 'carer')
			
				@include(config('settings.theme').'.gdpr.GdprCarer')
			
			@elseif($user->user_type == 'purchaser')
			
				@include(config('settings.theme').'.gdpr.GdprPurchaser')	
			
			@else
			
				@include(config('settings.theme').'.gdpr.GdprServiceUser')
			
			@endif
			
			  @include(config('settings.theme').'.gdpr.GdprMails')
					
					
		@else
		
		  <div class="financialsCard">
            <div class="financialsRow" style="text-align:center;display:block;">
				Please search by user id or name
            </div>
          </div>

		@endif

    </div>
    
</div>

<script>
$(document).ready(function(){	
	$('#gdprOption').change(function(){
		var opt = $(this).val();
		$('.formItem--search').val(opt);
	});
});
</script>

l/resources/views/HolmAdmin/gdpr/gdprToXls.blade.php
	@if(count($user)==1)
			
				
					@if($user->user_type == 'carer')
					
						@include(config('settings.theme').'.gdpr.gdprToXlsCarer')
					
					@elseif($user->user_type == 'purchaser')
					
						@include(config('settings.theme').'.gdpr.gdprToXlsPurchaser')	
					
					@else
					
						@include(config('settings.theme').'.gdpr.gdprToXlsServiceUser')
					
					@endif

					
		@else
		
		   No record found.


	@endif

l/resources/views/HolmAdmin/gdpr/gdprToXlsBonuses.blade.php
<?php use App\Http\Controllers\Admin\BonusController; ?>

<h4 style="color: navy;">Bonuses </h4>

<table class="adminTable">
            <thead>
            <tr>
                <td class=" ordninary-td ordninary-td--small no-padding-l">
                   Date
                </td>
                <td class=" ordninary-td ordninary-td--big ">
               
                  Benefactor name
                
                </td>
                <td class=" ordninary-td ordninary-td--small  ">
                  <span class="td-title td-title--invition">
                    Invitation Code
                  </span>

                </td>
                <td class=" ordninary-td ordninary-td--small  ">
                  <span class="td-title td-title--invition">
                    Referrer
                  </span>

                </td>
                <td class=" ordninary-td  ">
                  <span class="td-title td-title--paid-bonus">
                    Paid bonuses
                  </span>
                </td>
                <td class=" ordninary-td  no-padding-l">
                  <span class="td-title td-title--amount">
                    Amount
                  </span>
                </td>
            </tr>
            </thead>
            <tbody>
            @if($bonusPayouts->count())
                @foreach($bonusPayouts as $bonusPayout)
                    <tr>
                        <td>
                            {{$bonusPayout->created_at->format('d-m-Y')}}
                        </td>
                       <td class="">
                            {{$bonusPayout->user->full_name}}
                        </td>
                               
                        <td align="left">
                          @if(BonusController::user_referral_code($bonusPayout->id))
                                  {{BonusController::user_referral_code($bonusPayout->id)}}
                              @elseif($bonusPayout->user->use_register_code)
                                  REGISTER
                              @else
                                  -
                              @endif
                          
                        </td>
                        <td align="left">
                              @if($bonusPayout->bonus_type_id == 2)
                                  @foreach($users as $user)
                                      @if($user->id == $bonusPayout->referral_user_id)
                                        @if($user->user_type_id==1)
                                        {{$user->first_name}} {{$user->family_name}} 
                                        @else
                                        {{$user->first_name}} {{$user->family_name}}
                                        @endif
                                      @endif
                                  @endforeach
                              @elseif($bonusPayout->user->use_register_code)
                                  REGISTER
                              @else
                                  -
                              @endif

                        </td>
                        <td align="left">
                          {{$bonusPayout->user->paid_bonuses}}
                        </td>
                        <td align="left">
                           {{$bonusPayout->amount}}
                        </td>
                    </tr>
                @endforeach
                @endif
            </tbody>
        </table>
        

l/resources/views/HolmAdmin/gdpr/gdprToXlsDocuments.blade.php
<div class="financialsCard__title" style="width: 100%;">
    <h4 style="color: navy;">
       Uploaded Images 
    </h4>
</div>

<table>
@if($documents || $profileImage)

    @if($profileImage && file_exists(public_path('/img/profile_photos/' . $user->id . '.png')) )
         <tr>
            <th>Profile Image</th>
            <td>{{url('')}}{{$profileImage}}</td>
        </tr>
    @endif
    @if($documents)
        @foreach($documents as $document)
            <?php
                $supported_image = array(
                    'gif',
                    'jpg',
                    'jpeg',
                    'png'
                );

                $src_file_name = $document->file_name;
                $ext = strtolower(pathinfo($src_file_name, PATHINFO_EXTENSION)); // Using strtolower to overcome case sensitive
                if (in_array($ext, $supported_image)) {?>
                <tr>
                    <th>
                    @if($document->title=='undefined')
                        @if($document->type=='NVQ') 
                            Qualification 
                        @else
                             {{$document->type}}   
                        @endif
                       
                        
                    @else
                      {{$document->title}}
                    @endif  
                    
                    </th>
                    <td>{{url('')}}/api/document/{{$document->id}}/preview</td>
                </tr>
                    
               <?php } ?>
           
        @endforeach
    @endif
@else
    <tr><td>No images found.</td></tr>    
@endif    
</table>