l/routes/web.php
//Route::post('/saveCard/{cardData}', 'Bookings\PaymentsController@saveCard');
// /alexx


Route::group(['prefix' => 'admin','middleware'=> 'admin','namespace' => 'Admin'],function() {

    Route::get('/', 'AdminController@adminHomePage')->name('adminHomePage');
    Route::resource('/user','User\UserController', ['except' => ['show']]);
    Route::get('/user/getCarerImage/{id}','User\UserController@getCarerImage');
    Route::get('/user/page/{p?}','User\UserController@index')->name('user_pagination');;
    Route::resource('/booking','Booking\BookingController', ['only' => ['index']]);
//    Route::get('/blog/{id}', 'Blog\BlogController@create');
    Route::resource('/blog','Blog\BlogController');
//    Route::resource('/tags','Blog\TagController');

    Route::get('/user/review_management','ReviewManagementController@index')->name('ReviewManagement');
    Route::post('/user/review_management','ReviewManagementController@index')->name('ReviewManagement');
    Route::get('/user/review_management/{id}','ReviewManagementController@edit')->name('ReviewManagementEdit');
    Route::post('/user/review_management/{id}','ReviewManagementController@edit')->name('ReviewManagementEdit');
  
  	Route::get('/user/reviewed_management','ReviewManagementController@reviewed')->name('ReviewedManagement');
  	Route::post('/user/reviewed_management','ReviewManagementController@reviewed')->name('ReviewedManagement');
  	Route::get('/user/reviewed_management/{id}','ReviewManagementController@reviewed_edit')->name('ReviewManagementEdited');
    Route::post('/user/reviewed_management/{id}','ReviewManagementController@reviewed_edit')->name('ReviewManagementEditrd');

    Route::get('/financial','FinancialController@index')->name('financial');
    Route::get('/statistic','StatisticController@index')->name('statistic');
    Route::get('/statistic/download','StatisticController@exportStaticticsToXls')->name('statisticDownload');
    Route::get('/fees','FeesController@index')->name('fees');
   Route::get('/liveincarer','LiveincarerController@index')->name('liveincareres'); 
   Route::post('/liveincarer','LiveincarerController@update')->name('liveincarerpost');
    Route::get('/post-codes','PostCodesController@index')->name('PostCodes');
    Route::post('/post-codes','PostCodesController@index')->name('PostCodesPost');
    Route::post('/fees','FeesController@update')->name('feespost');
    Route::get('/holidays','HolidaysController@index')->name('holidays');
    Route::post('/holidays','HolidaysController@update')->name('holidaysPost');
    Route::post('/holidays/delete/{id}','HolidaysController@delete')->name('holidaysDeletePost');

    Route::get('/settings','SettingsController@index')->name('settingsAdmin');
    Route::post('/settings','SettingsController@update')->name('settingsAdminPost');
    Route::delete('/settings/{id}', 'SettingsController@deleteAdmin')->name('settingsAdminDelete');
	
  	Route::get('/add-carer-wages','CarerWagesController@create')->name('CarerWagesAdd');
    Route::get('/carer-wages','CarerWagesController@index')->name('CarerWages');
    Route::post('/carer-wages','CarerWagesController@update')->name('CarerWagesPost');
  	Route::post('/save-carer-wages','CarerWagesController@save')->name('CarerWagesSave');
  


    Route::get('/booking-transactions', 'AdminSitePayment@getBookingTransactions')->name('BookingTransactions');
    Route::post('/booking-transactions', 'AdminSitePayment@getBookingTransactions')->name('BookingTransactionsPost');

    Route::get('/carer-payout', 'AdminSitePayment@getPayoutsToCarers')->name('PayoutsToCarers');
    //Route::post('/carer-payout/{booking}', 'AdminSitePayment@makePayoutToCarer')->name('makePayoutToCarer');
    Route::post('/carer-payout/{appointment_id}', 'AdminSitePayment@makePayoutToCarer')->name('makePayoutToCarer');

    Route::get('/purchaser-payout', 'AdminSitePayment@getPayoutsToPurchasers')->name('PayoutsToPurchasers');
    Route::post('/purchaser-payout/{booking}', 'AdminSitePayment@makePayoutToPurchaser')->name('makePayoutToPurchaser');
  

    Route::get('/dispute-payout', 'DisputePayoutsController@index')->name('DisputePayouts');
    Route::put('/dispute-payout/{dispute_payout_id}/detailsOfDispute', 'DisputePayoutsController@setDetailsOfDispute');
    Route::put('/dispute-payout/{dispute_payout_id}/detailsOfDisputeResolution', 'DisputePayoutsController@detailsOfDisputeResolution');
    Route::post('/dispute-payout/{dispute_payout_id}/payoutToCarer', 'DisputePayoutsController@payoutToCarer');
    Route::post('/dispute-payout/{dispute_payout_id}/payoutToPurchaser', 'DisputePayoutsController@payoutToPurchaser');

    Route::get('/bonuses-carers', 'BonusController@getBonusesCarer')->name('BonusesCarers');
    Route::get('/bonuses-purchasers', 'BonusController@getBonusesPurchaser')->name('BonusesPurchasers');
    Route::post('/payout-bonus/{bonus_id}', 'BonusController@payoutBonus');
    Route::post('/cancel-bonus/{bonus_id}', 'BonusController@cancelBonus');

    //alexx
    Route::get('/filterCarerWages/{carerId}/{filter}', 'CarerWagesController@filterCarerWages');
    //returns all appointment statuses of a booking
  
   //add export on all admin pages 
	Route::get('/booking/download','Booking\BookingController@exportBookingToXls')->name('bookingDownload');
	Route::get('/booking-transactions/download','AdminSitePayment@exportTransactionToXls')->name('bookingTransactionDownload');
	Route::get('/purchaser-payout/download','AdminSitePayment@exportPurchaserPaymentToXls')->name('purchaserPaymentDownload');
	Route::get('/carer-payout/download','AdminSitePayment@exportCarerPaymentToXls')->name('carerPaymentDownload');
	Route::get('/dispute-payout/download','DisputePayoutsController@exportDisputePayoutToXls')->name('disputePayoutsDownload');
	Route::get('/bonuses-carers/download','BonusController@exportBonusCarersToXls')->name('bonusCarersDownload');
	Route::get('/bonuses-purchasers/download','BonusController@exportBonusPurchaserToXls')->name('bonusPurchaserDownload');
Route::get('/booking/accountant-report-download','Booking\BookingController@exportAccountantReportToXls')->name('accountantReportDownload');
Route::resource('/page','Page\PageController');
Route::resource('/faq','Faq\FaqController');
Route::resource('/trust','Trust\TrustController');
Route::resource('/testimonial','Testimonial\TestimonialController');
Route::resource('/banner','Banner\BannerController');  
Route::get('/contact','Contact\ContactController@index')->name('contactget');
Route::post('/contact-update','Contact\ContactController@update')->name('contactpost');  
Route::get('/gdpr','User\UserController@UserGdpr')->name('gdpr');
Route::get('/gdpr/download','User\UserController@exportGdprToXls')->name('gdprDownload');
Route::get('/ip-monitoring','User\UserController@ipMonitoring')->name('IpMonitoring');
  
Route::get('/booking/{booking_id}/cancelBooking','Booking\BookingController@cancelBooking');
Route::get('/booking/{appointment_id}/cancelAppointment','Booking\BookingController@cancelAppointment');
Route::get('/bonuses-purchasers/credit-wallet/', 'BonusController@CreditWallet');  
  
});

Route::get('/check24/{date}/{time}', 'Bookings\BookingsController@appointmentIsMinimum24HoursAhead');

Route::post('/increase-postcode-search/{postcode}', 'SearchController@increasePostCode');
Route::get('/get-referral-code/{userId}', 'CarerController@getReferralCode');
Route::post('/update-referral-code/{userId}/{code}', 'CarerController@updateReferralCode');

Route::get('/test-cronjob', 'CarerController@testCronjob');


Route::get('/test_document_upload', function (){
    return view('test_document_upload');
});

Route::get('/appan', function (){
    return view('resources/views/Holm/purchaserProfiles/Booking/NewAnAppointment');
});

Route::get('/test_stripe', function (){
    $user = \App\User::find(2);
    $card = $user->credit_cards()->first();
    \App\Helpers\Facades\PaymentTools::createCharge(2000, $card->token, 209);
});

/*Route::group(['prefix' => 'laravel-filemanager', 'middleware' => ['web', 'auth']], function () {
     \UniSharp\LaravelFilemanager\Lfm::routes();
 });*/

Route::get('/test', function () {
  
 // echo K1rkhnmmn=
   //return bcrypt('K1rkhnmmn=');
  $res = DB::select("SELECT a.id FROM appointments a JOIN bookings b ON a.booking_id = b.id WHERE UNIX_TIMESTAMP(a.date_start) = CURDATE() AND DATE_ADD(NOW(), INTERVAL 1 HOUR) > UNIX_TIMESTAMP(a.time_from) AND a.reminder_sent = 0 AND b.status_id = 5 AND a.status_id < 3");
  echo "<pre>"; print_r($res); echo "<pre>"; exit;
//    $pathes = [
//        'img/profile_photos',
//        'img/service_user_profile_photos',
//    ];
//
//    foreach ($pathes as $path) {
//        $photos = File::allFiles($path);
//        foreach ($photos as $photo) {
//            $name = $photo->getPathname();
//
//            try {
//                $img = Image::make($name);
//                $width = $img->width();
//                $height = $img->height();
//
//                if ($width / $height > 1) {
//                    // resize image to new width but do not exceed original size
//                    $img = $img->widen(112, function ($constraint) {
//                        $constraint->upsize();
//                    });
//                } else {
//                    // resize image to new height but do not exceed original size
//                    $img = $img->heighten(112, function ($constraint) {
//                        $constraint->upsize();
//                    });
//                }
//
//                $img->save($name);
//            } catch (\Exception $e) {
//                echo 'error ' . $name . '<br>';
//            }
//        }
//    }
//    $a = 1.3;
//    $b = 1.3;
//
//    $sum = $a + $b;
//
//    $a = \Carbon\Carbon::createFromFormat('H.i', $a);
//    $aa = $a->addHours($b);
//    dd($aa->diffInHours($a))
//    $b = \Carbon\Carbon::createFromFormat('H.i', $b);
////    $a = \Carbon\Carbon::parse($a);
//    $a->addHours($b);

l/app/Trust.php
<?php

namespace App;

use DateTime;
use Illuminate\Database\Eloquent\Model;

class Trust extends Model
{
    protected $fillable = ['title'];


    public function user()
    {
        return $this->belongsTo(User::class);
    }

}

l/app/Http/Controllers/Admin/Trust/TrustController.php
<?php

namespace App\Http\Controllers\Admin\Trust;
use App\Http\Controllers\Admin\AdminController;

use App\Trust;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Hash;


class TrustController extends AdminController
{
    private $trust;

    public function __construct(Trust $trust) {
        parent::__construct();
        $this->trust = $trust;

        $this->template = config('settings.theme').'.templates.adminBase';
    }


    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $this->title = 'Admin Trusts';
        $trusts = Trust::orderBy('id', 'desc')->get();
        $this->vars = array_add($this->vars,'trusts',$trusts);
        $this->content = view(config('settings.theme').'.trust.trust')->with($this->vars)->render();

        return $this->renderOutput();
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $this->title = 'Admin Trusts';
        $this->content = view(config('settings.theme') . '.trust.create')->with($this->vars)->render();

        return $this->renderOutput();
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'title' => 'required'
         
        ]);

        $trust = new Trust;
        $trust->title = $request->title;
        $trust->url = $request->url;
        $trust->image_alt = $request->image_alt;
        $trust->status = 'published';
      	$itemreq = $request;
      	$download_file_name = "";
          	 if( $itemreq->hasFile('trustImage')){ 
                $image = $itemreq->file('trustImage'); 
                $image_path=base_path('public/image_Association');
                $fileName = $image->getClientOriginalName();
                $fileExtension = $image->getClientOriginalExtension();
                $download_file_name=time().'.'.$fileExtension;
                $image->move($image_path,$download_file_name);
                $trust->image_path = $download_file_name;
            }
        $trust->save();
        return redirect(route('trust.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($trustId)
    {
        $this->title = 'Admin Trusts';
        $trusts = $this->trust->findOrFail($trustId);
        $this->vars = array_add($this->vars,'trust',$trusts);
        $this->content = view(config('settings.theme').'.trust.edit')->with($this->vars)->render();
        return $this->renderOutput();

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
		if (isset($request->delete_trust_id)) {
            $trust = Trust::find($request->delete_trust_id);
            $trust->delete();
            return response(['status' => 'success']);
        }elseif($request->publish_trust_id){
			 $trust = Trust::find($request->publish_trust_id);
			 $trust->status = 'published';	
			 $trust->save();
            return response(['status' => 'success']);	
		}else{
           
      		$download_file_name = "";
            $trust = Trust::find($id);
            $trust->title = $request->title;
            $trust->url = $request->url;
            $trust->image_alt = $request->image_alt;
            //$trust->image_path = $request->image;
            $trust->status = 'published';
             $itemreq = $request;
          	 if( $itemreq->hasFile('trustImage')){ 
                $image = $itemreq->file('trustImage'); 
                $image_path=base_path('public/image_Association');
                $fileName = $image->getClientOriginalName();
                $fileExtension = $image->getClientOriginalExtension();
                $download_file_name=time().'.'.$fileExtension;
                $image->move($image_path,$download_file_name);
                $trust->image_path = $download_file_name;
            }
            $trust->save();
            return redirect(route('trust.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

l/resources/views/HolmAdmin/trust/create.blade.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/dist/bootstrap-tagsinput.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>



<div class="mainPanel">
    <h2 class="categoryTitle">
          <span class="categoryTitle__ico">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
          </span>
        Trust -> Create
    </h2>
    <div class="contentCard">
        <div class="contentCard__head contentCard__head--payment">
            <h2>Trust</h2>
        </div>
        <form role="form" action="{{ route('trust.store') }}" method="post" enctype="multipart/form-data">
            <div class="contentBody">
				
				
                <div class="fieldRow">
                    <div class="formField formField--full ">
                        <h2 class="fieldLabel">Title</h2>
                        <div class="fieldWrap">
                            <input type="text" name="title" class="formItem formItem--without-ico"
                                   placeholder="Enter the title">
                        </div>
                    </div>
                </div>

                <div class="fieldRow">
                    <div class="formField formField--full ">
                        <h2 class="fieldLabel">URL</h2>
                        <div class="fieldWrap">
                            <input name="url" type="text" class="formItem formItem--without-ico"
                                   placeholder="Enter the URL">
                        </div>
                    </div>
                </div>
                
                <div class="fieldRow">
                    <div class="formField  formField--full">
                        <h2 class="fieldLabel">Image</h2>
                        <div class="fieldWrap">  
                            <input type="file" name="trustImage" /><br>
                            <input type="text" name="image_alt" placeholder="Image alt text"/>
                        </div>
                    </div>
                </div>

                <div class="settingBtn">
                    <input type="submit" class="actionsBtn actionsBtn--accept actionsBtn--big actionsBtn--no-centered"
                           value="Create">
                </div>
            </div>
        </form>
    </div>
</div>

l/resources/views/HolmAdmin/trust/edit.blade.php
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/css/bootstrap.min.css">
<link rel="stylesheet" href="http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/dist/bootstrap-tagsinput.css">
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://bootstrap-tagsinput.github.io/bootstrap-tagsinput/dist/bootstrap-tagsinput.min.js"></script>


<div class="mainPanel">
    <h2 class="categoryTitle">
          <span class="categoryTitle__ico">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
          </span>
        Trust -> Edit
    </h2>
    <div class="contentCard">
        <div class="contentCard__head contentCard__head--payment">
            <h2>Trust</h2>
        </div>
        <form role="form" action="{{ route('trust.update', $trust->id) }}" method="post" id="trustImageUpload" enctype="multipart/form-data">
            {{ csrf_field() }}
            {{ method_field('PATCH') }}
            <div class="contentBody">
                <div class="fieldRow">
                    <div class="formField formField--full ">
                        <h2 class="fieldLabel">Title</h2>
                        <div class="fieldWrap">
                            <input name="title" type="text" class="formItem formItem--without-ico"
                                   placeholder="Enter the title" value="{{ $trust->title }}">
                        </div>
                    </div>
                </div>

                <div class="fieldRow">
                    <div class="formField formField--full ">
                        <h2 class="fieldLabel">URL</h2>
                        <div class="fieldWrap">
                            <input name="url" type="text" class="formItem formItem--without-ico"
                                   placeholder="Enter the URL" value="{{ $trust->url }}">
                        </div>
                    </div>
                </div>
 
                <div class="fieldRow">
                    <div class="formField  formField--full">
                        <h2 class="fieldLabel">Image</h2>
                        <div class="fieldWrap">  
                            <input type="file" name="trustImage" /><br>
                          	 @if(!empty($trust->image_path))
                               <img src="{{URL::to('/')}}/public/image_Association/{{$trust->image_path}}" width="100"/><br>
                             @endif
                             <input type="text" name="image_alt" placeholder="Image alt text" value="{{$trust->image_alt}}"/>
                        </div>
                    </div>
                </div>

                <div class="settingBtn">
                    <input type="submit" class="actionsBtn actionsBtn--accept actionsBtn--big actionsBtn--no-centered"
                           value="update">
                </div>
            </div>
        </form>
    </div>
</div>
<script>
$(document).ready(function(){
	
		   
        var idLoadFiles = '#trustImageUpload';
        
	    $(idLoadFiles).find('.pickfiles').attr("disabled", false);
        $(idLoadFiles).find('.pickfiles-change').attr("disabled", false);
        $(idLoadFiles).find('.pickfiles_profile_photo--change').attr("disabled", false);
        $(idLoadFiles).find('.pickfiles_profile_photo_service_user--change').attr("disabled", false);
        $(idLoadFiles).find('.pickfiles-delete').attr("style", 'display: block');
        $(idLoadFiles).find('.addInfo__input-ford').attr("disabled", false).removeClass('profileField__input--greyBg');
        $(idLoadFiles).find('.addInfo__input-ford').attr("readonly", false).removeClass('profileField__input--greyBg');



});

</script>

l/resources/views/HolmAdmin/trust/trust.blade.php
<div class="mainPanel">
    <h2 class="categoryTitle">
          <span class="categoryTitle__ico">
            <i class="fa fa-newspaper-o" aria-hidden="true"></i>
          </span>
        Trusts
    </h2>
    <div class="settingBtn">
        <a href="{{ route('trust.create') }}"
           class="actionsBtn actionsBtn--accept actionsBtn--big actionsBtn--no-centered">
            Create Trust
        </a>

    </div>
    <div class="tableWrap tableWrap--margin-t">
        <table class="adminTable">
            <thead>
            <tr>
                <td class="orderNumber">
                    <span class="td-title td-title--number">
                     №
                    </span>
                </td>

                <td class=" ordninary-td ">
                    <span class="td-title td-title--title">
                    title
                    </span>

                </td>
                <td class=" ordninary-td  ">
                    <span class="td-title td-title--time">
                      Image
                    </span>
                </td>
                <td class=" ordninary-td ">
                    <span class="td-title td-title--actions">
                      actions
                    </span>
                </td>
                <td class=" ordninary-td ">
                    <span class="td-title td-title--status">
                    Status
                    </span>
                </td>
                
                
            </tr>
            </thead>

            <tbody>
            @foreach($trusts as $trust)
                <tr>
                    <td>
                        <span>{{ $trust->id }}</span>
                    </td>

                    <td class="">
                        <span>{{ $trust->title }}</span>
                    </td>
                    <td>
                       <div class="profStatus profStatus--left">
                            @if(!empty($trust->image_path))
                               <img src="{{URL::to('/')}}/public/image_Association/{{$trust->image_path}}" width="100"/>
                            @endif
                        </div>
                    </td>
                    <td>
                        <div class="actionsGroup">
                             @if($trust->status == 'published')
                                <a href="{{ route('trust.edit', $trust->id) }}" class="actionsBtn actionsBtn--edit  ">
                                    edit
                                </a>
                                <a data-delete_trust_id="{{ $trust->id }}"
                                   class="actionsBtn actionsBtn--delete deleteTrust">
                                    delete
                                </a>
                            @elseif($trust->status == 'deleted')
                                <a data-publish_trust_id="{{ $trust->id }}"
                                   class="actionsBtn actionsBtn--accept publishTrust">
                                    publish
                                </a>
                                <a href="{{ route('trust.edit', $trust->id) }}" class="actionsBtn actionsBtn--edit  ">
                                    edit
                                </a>
                            @endif
                        </div>
                    </td>
                    <td>
						@if($trust->status == 'published')
							<span class="profStatus__item profStatus__item--new">published</span>
						@elseif($trust->status == 'deleted')
							<span class="profStatus__item profStatus__item--canceled"> deleted</span>
						@endif
                    </td>
                </tr>
            @endforeach
            </tbody>
        </table>
    </div>
   

    
    
    

<script>
    $(document).ready(function () {
        $('.adminTable').on('click', '.deleteTrust', function (e) {
            e.preventDefault();
            var trust_id = $(this).attr('data-delete_trust_id');
            $.ajax({
                url: '/l/admin/trust/' + trust_id,
                type: 'PUT',
                data: {'delete_trust_id': trust_id},
                success: function () {
                    location.reload();
                },
                error: function () {
                    console.log('fail');
                }
            });
        });
        
        $('.adminTable').on('click', '.publishTrust', function (e) {
            e.preventDefault();
            var trust_id = $(this).attr('data-publish_trust_id');
            $.ajax({
                url: '/l/admin/trust/' + trust_id,
                type: 'PUT',
                data: {'publish_trust_id': trust_id},
                success: function () {
                    location.reload();
                },
                error: function () {
                    console.log('fail');
                }
            });
        });

    
    });
</script>